import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
print("\n--- SECTION 1: Data Loading and Initial Inspection ---")
df = pd.read_csv("hour.csv")
df['dteday'] = pd.to_datetime(df['dteday'])
df = df.sort_values(['dteday', 'hr']).reset_index(drop=True)
print("\nDataset Information:")
df.info()
print("\nFirst 5 rows of the dataset:")
print(df.head())
print("\n--- SECTION 2: Exploratory Data Analysis (EDA) ---")
plt.figure(figsize=(15, 6))
plt.plot(df['dteday'], df['cnt'], alpha=0.6, color='skyblue')
plt.title('Hourly Bike Rental Demand Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Rentals (cnt)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('rental_over_time_learning.png')
plt.close()
print("Generated 'Hourly Bike Rental Demand Over Time' plot.")
fig, axes = plt.subplots(3, 1, figsize=(12, 18))
sns.boxplot(data=df, x='hr', y='cnt', ax=axes[0], palette='viridis')
axes[0].set_title('Hourly Rental Pattern', fontsize=14)
axes[0].set_xlabel('Hour of Day (0-23)', fontsize=12)
axes[0].set_ylabel('Total Rentals', fontsize=12)
sns.boxplot(data=df, x='weekday', y='cnt', ax=axes[1], palette='magma')
axes[1].set_title('Daily Rental Pattern (0=Sunday, 6=Saturday)', fontsize=14)
axes[1].set_xlabel('Day of Week', fontsize=12)
axes[1].set_ylabel('Total Rentals', fontsize=12)
sns.boxplot(data=df, x='season', y='cnt', ax=axes[2], palette='cividis')
axes[2].set_title('Seasonal Rental Pattern (1:Spring, 2:Summer, 3:Fall, 4:Winter)', fontsize=14)
axes[2].set_xlabel('Season', fontsize=12)
axes[2].set_ylabel('Total Rentals', fontsize=12)
plt.tight_layout()
plt.savefig('patterns_learning.png')
plt.close()
print("Generated 'Hourly, Daily, and Seasonal Patterns' plots.")
plt.figure(figsize=(10, 5))
plot_acf(df['cnt'], lags=48, ax=plt.gca(), title='Autocorrelation of Rental Demand (up to 48 hours)')
plt.xlabel('Lag (Hours)', fontsize=12)
plt.ylabel('Autocorrelation', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('acf_learning.png')
plt.close()
print("Generated 'Autocorrelation Function (ACF)' plot.")
df_daily = df.set_index('dteday')['cnt'].resample('D').mean()
result = seasonal_decompose(df_daily, model='additive', period=365)
fig = result.plot()
fig.set_size_inches(12, 10) 
plt.suptitle('Time Series Decomposition of Daily Mean Rentals', y=1.02, fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.98]) 
plt.savefig('decomposition_learning.png')
plt.close()
print("Generated 'Time Series Decomposition' plot.")
print("\n--- SECTION 3: Feature Engineering ---")
df['lag_1h'] = df['cnt'].shift(1)     
df['lag_2h'] = df['cnt'].shift(2)     
df['lag_24h'] = df['cnt'].shift(24)   
print("Created lag features: lag_1h, lag_2h, lag_24h.")
df['rolling_mean_6h'] = df['cnt'].shift(1).rolling(window=6).mean()
print("Created rolling mean feature: rolling_mean_6h.")
df_fe = df.dropna().reset_index(drop=True)
print(f"Original rows: {len(df)}. Rows after dropping NaNs: {len(df_fe)}.")
features = ['hr', 'weekday', 'mnth', 'yr', 'season', 'holiday', 'workingday',
            'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
            'lag_1h', 'lag_2h', 'lag_24h', 'rolling_mean_6h']
target = 'cnt'
print("\n--- SECTION 4: Model Training and Evaluation ---")
split_idx = int(len(df_fe) * 0.8)
train = df_fe.iloc[:split_idx] 
test = df_fe.iloc[split_idx:]  

X_train, y_train = train[features], train[target]
X_test, y_test = test[features], test[target]
print(f"Data split: Training samples = {len(train)}, Testing samples = {len(test)}.")
y_baseline = X_test['lag_1h']
mae_baseline = mean_absolute_error(y_test, y_baseline)
rmse_baseline = np.sqrt(mean_squared_error(y_test, y_baseline))
print(f"\nBaseline (Naive - previous hour's demand) MAE: {mae_baseline:.2f}")
print(f"Baseline (Naive - previous hour's demand) RMSE: {rmse_baseline:.2f}")
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
print("\nTraining Random Forest Regressor...")
model.fit(X_train, y_train)
print("Random Forest Regressor training complete.")
y_pred = model.predict(X_test)
mae_model = mean_absolute_error(y_test, y_pred)
rmse_model = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"\nRandom Forest Model MAE: {mae_model:.2f}")
print(f"Random Forest Model RMSE: {rmse_model:.2f}")
plt.figure(figsize=(15, 6))
plt.plot(test['dteday'].iloc[:168], y_test.iloc[:168], label='Actual Rentals', color='blue', alpha=0.7)
plt.plot(test['dteday'].iloc[:168], y_pred[:168], label='Predicted Rentals', color='red', alpha=0.7, linestyle='--')
plt.title('Actual vs. Predicted Bike Rentals (First Week of Test Set)', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Rentals', fontsize=12)
plt.legend(fontsize=10)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('predictions_learning.png')
plt.close()
print("Generated 'Actual vs. Predicted Bike Rentals' plot.")
importances = model.feature_importances_
feat_importances = pd.Series(importances, index=features)
plt.figure(figsize=(10, 6))
feat_importances.nlargest(10).plot(kind='barh', color='teal')
plt.title('Top 10 Feature Importances from Random Forest Model', fontsize=16)
plt.xlabel('Importance Score', fontsize=12)
plt.ylabel('Feature', fontsize=12)
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('feature_importance_learning.png')
plt.close()
print("Generated 'Feature Importance' plot.")
print("-----Completed-----")